# Permalinks
permalink:           pretty

# Setup
title:               knupth's blog
tagline:             A place that exists
url:                 knupth.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              knupth
  url:               http://knupth.github.io
  email:             knupth@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/knupth/knupth.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
